---
title: "git_01"
author: "Zanya Davenport"
date: "Summer 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
  
Little Birds are dining  
Warily and well,  
Hid in mossy cell:  
Hid, I say, by waiters  
Gorgeous in their gaiters  
  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
  
Something there is that doesn’t love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:  
  
  
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
  
“The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make  
The billows smooth and bright —  
And this was odd, because it was  
The middle of the night.  
  
The moon was shining sulkily,  
Because she thought the sun  
Had got no business to be there  
After the day was done —  
“It’s very rude of him,” she said,  
“To come and spoil the fun.”  
  
## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
  
Here on the edge of hell  
Stands Harlem—  
Remembering the old lies,  
The old kicks in the back,  
The old “Be patient”  
They told us before.  
Sure, we remember.  
Now when the man at the corner store  
Says sugar’s gone up another two cents,  
And bread one,  
And there’s a new tax on cigarettes—  
We remember the job we never had,  
Never could get,  
And can’t have now  
Because we’re colored.  
  
  